[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  NODE_ENV = "production"
  # Ensure devDependencies (vite, plugins, etc.) are installed during Netlify builds
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
